### ISSUE TITLE
请完善相关Markdown的描述

### ISSUE THREAD

**Issue by LambertW** [uliian/easyRBAC#4]
项目捣鼓着跑起来了，但是有很多细节的东西没有描述。
例如 
1. 运行环境 ：.NET Core + MySql；
2. 登陆账号密码
3. 前后端项目运行的步骤
4. 相关RBAC设计理念介绍。

如果有关联博文的话，是否可以发个链接学习一下？

**Comment by uliian** [comment]
OK~没有问题，因为这个项目开发之初只是想我自己用，Readme和项目名都有很多戏谑的成分在里面。没想到被大家关注了。我争取在一周之内写一份部署文档和概念描述出来！感谢您的关注

**Comment by LambertW** [comment]
看到 张善友老师 在其他地方发了链接，就来看看实现到什么程度了。
看起来基本功能都实现了，感谢您的付出！

**Comment by uliian** [comment]
已经写了一部分了，你试试，有什么问题可以和我说

**Comment by LambertW** [comment]
很高效，已经跑起来了~
对于权限【资源】这块的设计，粒度是到什么程度？如何比较合理的使用，如果有时间再完善一下这块就好了，感谢~
